export const SET_BREEDS_LIST = 'SET_BREEDS_LIST';
export const SET_BREED_FORM_DATA = 'SET_BREED_FORM_DATA';
export const SET_GENERATED_IMAGES = 'SET_GENERATED_IMAGES';
export const SET_ALERT_DATA = 'SET_ALERT_DATA';
